on:
  push:
    branches:
      - main
  schedule:
    - cron: '13 12 * * *'

jobs:
  gh-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install Nim
        uses: iffy/install-nim@v3
      - name: install dependencies
        run: nimble install -y nimib puppy rss
      - name: gather feeds and create reader page
        run: nim r -d:release index
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
